export interface User {
    userId?: number;       // Optional, as it will be generated by the backend
    username: string;
    passwordHash: string;
    role: string;
    email: string;
    phoneNumber?: string;  // Optional
    dateCreated?: Date;    // Optional, can be assigned by the backend
    lastLogin?: Date;      // Optional
  }
  